[package]
name = "snownet"
version = "0.1.0"
edition = "2021"
license = { workspace = true }

[dependencies]
backoff = "0.4.0"
boringtun = { workspace = true }
bytecodec = "0.4.15"
bytes = "1.7.1"
firezone-logging = { workspace = true }
hex = "0.4.0"
hex-display = "0.3.0"
ip-packet = { workspace = true }
itertools = "0.13"
once_cell = "1.17.1"
rand = "0.8"
secrecy = { workspace = true }
sha2 = "0.10.8"
str0m = { workspace = true }
stun_codec = "0.3.4"
thiserror = "1"
tracing = { workspace = true }

[lints]
workspace = true
