[package]
name = "snownet"
# mark:automatic-version
version = "1.0.0"
edition = "2021"

[dependencies]
anyhow = "1"
boringtun = { workspace = true }
firezone-relay = { workspace = true }
pnet_packet = { version = "0.34" }
rand = "0.8"
secrecy = { workspace = true }
str0m = { workspace = true }
thiserror = "1"
tracing = { workspace = true }
stun_codec = "0.3.4"
bytecodec = "0.4.15"
bytes = "1.4.0"
once_cell = "1.17.1"
backoff = "0.4.0"
hex = "0.4.0"
