repos:
  - repo: local
    hooks:
      # Elixir config
      - id: mix-compile
        name: 'elixir: mix compile'
        entry: mix compile --force --warnings-as-errors
        language: system
        pass_filenames: false
        files: \.ex$
      - id: mix-format
        name: 'elixir: mix format'
        entry: mix format --check-formatted
        language: system
      - id: mix-lint
        name: 'elixir: mix credo'
        entry: mix credo --strict
        language: system
        pass_filenames: false
        files: \.exs*$
      - id: mix-analysis
        name: 'elixir: mix dialyzer'
        entry: mix dialyzer --format dialyxir
        language: system
        pass_filenames: false
        files: \.exs*$
      - id: codespell
        name: 'python: codespell'
        entry: codespell
        language: system
        pass_filenames: false
      - id: rubocop
        name: 'ruby: rubocop'
        entry: bundle exec rubocop
        language: system
        pass_filenames: false
        files: \.rb$
      - id: markdownlint
        name: 'nodejs: markdownlint'
        entry: ./docs/node_modules/markdownlint-cli/markdownlint.js
        language: system
        pass_filenames: true
        files: docs/.*\.md$

  # Standard pre-commit hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: mixed-line-ending
        args: ['--fix=lf']
        description: Forces to replace line ending by the UNIX 'lf' character.
      - id: check-yaml
      - id: check-merge-conflict
      - id: end-of-file-fixer
        exclude: "^omnibus/config/patches/"
      - id: trailing-whitespace
        exclude: "^omnibus/config/patches/"
      - id: check-merge-conflict
      - id: no-commit-to-branch
        args:
          - -b
          - master
          - --pattern
          - '^(?!((chore|feat|feature|bug|fix|build|ci|docs|style|refactor|perf|test|revert)\/[a-zA-Z0-9\-\.\/]+)$).*'
