[package]
name = "http-client"
version = "0.1.0"
edition = { workspace = true }
license = { workspace = true }

[lib]
path = "lib.rs"

[dependencies]
anyhow = { workspace = true }
bytes = { workspace = true }
http = { workspace = true }
http-body-util = { workspace = true }
hyper = { workspace = true, features = ["client", "http2"] }
hyper-util = { workspace = true, features = ["tokio"] }
rustls = { workspace = true }
rustls-pki-types = { workspace = true }
socket-factory = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-rustls = { workspace = true }
tokio-util = { workspace = true, features = ["rt"] }
tracing = { workspace = true }
webpki-roots = { workspace = true }

[dev-dependencies]
futures = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt"] }

[lints]
workspace = true
