[package]
name = "connlib-client-apple"
# mark:next-apple-version
version = "1.3.8"
edition = "2021"

[build-dependencies]
swift-bridge-build = "0.1.57"

[dependencies]
anyhow = "1.0.86"
backoff = "0.4.0"
connlib-client-shared = { workspace = true }
connlib-model = { workspace = true }
firezone-logging = { workspace = true }
firezone-telemetry = { workspace = true }
ip_network = "0.4"
libc = "0.2"
phoenix-channel = { workspace = true }
rustls = { workspace = true }
secrecy = { workspace = true }
serde_json = "1"
socket-factory = { workspace = true }
swift-bridge = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread"] }
tracing = { workspace = true }
tracing-appender = "0.2"
tracing-subscriber = "0.3"
tun = { workspace = true }
url = "2.5.2"

[target.'cfg(any(target_os = "macos", target_os = "ios"))'.dependencies]
oslog = { version = "0.2.0", default-features = false }

[lib]
name = "connlib"
crate-type = ["staticlib"]
doc = false

[lints]
workspace = true
