[package]
name = "connlib-client-apple"
# mark:next-apple-version
version = "1.0.6"
edition = "2021"

[features]
mock = ["connlib-client-shared/mock"]

[build-dependencies]
swift-bridge-build = "0.1.53"

[dependencies]
secrecy = { workspace = true }
ip_network = "0.4"
libc = "0.2"
swift-bridge = { workspace = true }
connlib-client-shared = { workspace = true }
serde_json = "1"
tracing = { workspace = true }
tracing-oslog = { git = "https://github.com/Absolucy/tracing-oslog", branch = "main" } # Waiting for a release.
tracing-subscriber = "0.3"
tracing-appender = "0.2"
url = "2.5.0"
tokio = { version = "1.38", default-features = false, features = ["rt"] }

[lib]
name = "connlib"
crate-type = ["staticlib"]
doc = false

[lints]
workspace = true
