#cloud-config

write_files:
  - path: /etc/otelcol-contrib/config.yaml
    permissions: "0644"
    owner: root
    content: |
      receivers:
        otlp:
          protocols:
            http:
              endpoint: localhost:4318
      exporters:
        googlecloud:
          log:
            default_log_name: opentelemetry.io/collector-exported-log
      processors:
        memory_limiter:
          check_interval: 1s
          limit_percentage: 65
          spike_limit_percentage: 20
        batch:
        resourcedetection:
          detectors: [gcp]
          timeout: 10s
        filter/drophttp:
          error_mode: ignore
          traces:
            span:
              - 'attributes["http.target"] == "/healthz"'
      service:
        pipelines:
          traces:
            receivers: [otlp]
            processors: [memory_limiter, filter/drophttp, batch]
            exporters: [googlecloud]
          metrics:
            receivers: [otlp]
            processors: [memory_limiter, filter/drophttp, batch]
            exporters: [googlecloud]
          logs:
            receivers: [otlp]
            processors: [memory_limiter, filter/drophttp, batch]
            exporters: [googlecloud]

  - path: /etc/systemd/system/otel-collector.service
    permissions: "0644"
    owner: root
    content: |
      [Unit]
      Description=Start an OpenTelemetry collector docker container

      [Service]
      TimeoutStartSec=0
      Restart=always
      ExecStartPre=/usr/bin/docker pull otel/opentelemetry-collector-contrib:0.119.0
      ExecStart=/usr/bin/docker run --rm -u 2000 --name=otel-collector --network host --volume /etc/otelcol-contrib/:/etc/otelcol-contrib/ otel/opentelemetry-collector-contrib:0.119.0
      ExecStop=/usr/bin/docker stop otel-collector
      ExecStopPost=/usr/bin/docker rm otel-collector

  - path: /etc/iptables/rules.v6
    permissions: "0644"
    owner: root
    content: |
      *filter
      :INPUT DROP [0:0]
      :FORWARD DROP [0:0]
      :OUTPUT DROP [0:0]
      :DOCKER - [0:0]
      :DOCKER-ISOLATION-STAGE-1 - [0:0]
      :DOCKER-ISOLATION-STAGE-2 - [0:0]
      :DOCKER-USER - [0:0]
      -A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
      -A INPUT -i lo -j ACCEPT
      -A INPUT -p ipv6-icmp -j ACCEPT
      -A INPUT -p tcp -m tcp --dport 22 -j ACCEPT
      -A INPUT -p tcp -j ACCEPT
      -A INPUT -p udp -j ACCEPT
      -A FORWARD -j DOCKER-USER
      -A FORWARD -j DOCKER-ISOLATION-STAGE-1
      -A FORWARD -o docker0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
      -A FORWARD -o docker0 -j DOCKER
      -A FORWARD -i docker0 ! -o docker0 -j ACCEPT
      -A FORWARD -i docker0 -o docker0 -j ACCEPT
      -A FORWARD -p tcp -j ACCEPT
      -A FORWARD -p udp -j ACCEPT
      -A FORWARD -p ipv6-icmp -j ACCEPT
      -A OUTPUT -m state --state NEW,RELATED,ESTABLISHED -j ACCEPT
      -A OUTPUT -o lo -j ACCEPT
      -A DOCKER-ISOLATION-STAGE-1 -i docker0 ! -o docker0 -j DOCKER-ISOLATION-STAGE-2
      -A DOCKER-ISOLATION-STAGE-1 -j RETURN
      -A DOCKER-ISOLATION-STAGE-2 -o docker0 -j DROP
      -A DOCKER-ISOLATION-STAGE-2 -j RETURN
      -A DOCKER-USER -j RETURN
      COMMIT

runcmd:
  - sudo ip6tables-restore < /etc/iptables/rules.v6
  - systemctl daemon-reload
  - systemctl start otel-collector.service
