[package]
name = "anyhow-ext"
version = "0.1.0"
edition = { workspace = true }
license = { workspace = true }

[lib]
path = "lib.rs"

[dependencies]
anyhow = { workspace = true }

[dev-dependencies]
thiserror = { workspace = true }
