# UniFFI Configuration for client-ffi

[bindings.swift]
generate_immutable_records = true
generate_codable_conformance = true
generate_case_iterable_conformance = true

[bindings.kotlin]
android = true
generate_immutable_records = true
