[package]
name = "subzone"
version = "0.1.0"
keywords = ["command", "process", "subprocess", "worker"]
description = "Worker subprocesses with async IPC for Windows"
edition = "2021"

[dependencies]
anyhow = { version = "1.0" }
clap = { version = "4.4", features = ["derive",  "env"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = { version = "1.0", default-features = false }
tokio = { version = "1.33.0", features = ["io-util", "net", "process", "rt-multi-thread", "sync", "time"] }
tracing = { workspace = true }
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
uuid = { version = "1.7.0", features = ["v4"] }

[target.'cfg(windows)'.dependencies.windows]
version = "0.52.0"
features = [
  # Needed for `CreateJobObjectA`
  "Win32_Foundation",
  # Needed for `CreateJobObjectA`
  "Win32_Security",
  # Needed for Windows to automatically kill child processes if the main process crashes
  "Win32_System_JobObjects",
  # Needed to check process ID of named pipe clients
  "Win32_System_Pipes",
  "Win32_System_Threading",
]
