name: Sync APT repository metadata
run-name: Triggered by ${{ github.actor }}
on:
  workflow_dispatch:
  workflow_call:

concurrency:
  group: "create-apt-repository" # Unique group name to force only a single job at a time.
  cancel-in-progress: false

jobs:
  create-apt-repository-metadata:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup-azure-cli

      - uses: ./.github/actions/setup-gpg
        id: setup-gpg
        with:
          key: ${{ secrets.APT_REPOSITORY_GPG_KEY }}
          email: packages@firezone.dev

      - run: scripts/sync-apt.sh
        env:
          AZURERM_ARTIFACTS_CONNECTION_STRING: ${{ secrets.AZURERM_ARTIFACTS_CONNECTION_STRING }}
          GPG_KEY_ID: ${{ steps.setup-gpg.outputs.key_id }}
