# Workaround for the problem described here:
# https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/troubleshooting-required-status-checks
name: Elixir
on:
  merge_group:
    types: [checks_requested]
  pull_request:
    paths-ignore:
      - "elixir/**"
      - ".github/workflows/elixir.yml"
  workflow_call:

jobs:
  elixir_unit-test:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "no build required"'
  elixir_type-check:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "no build required"'
  elixir_static-analysis:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "no build required"'
  elixir_migrations-and-seed-test:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "no build required"'
  elixir_acceptance-test:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "no build required"'
  elixir_web-container-build:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "no build required"'
  elixir_api-container-build:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "no build required"'
