name: Publish packages to GitHub Packages
on:
  release:
    types: [published]
jobs:
  # Noop: XCFramework is attached to release already in build workflow
  # publish-apple:
  publish-android:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./rust
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: ./rust
      - name: Setup toolchain
        run: rustup show
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Sanity check tag equals AAR version
        run: |
          pkg_version=$(awk -F ' = ' '$1 ~ /version/ { gsub(/[\"]/, "", $2); printf("%s",$2); exit; }' connlib/android/lib/build.gradle.kts)
          if [[ "${{ github.ref_name }}" = "$pkg_version" ]]; then
            echo "Github ref name ${{ github.ref_name }} equals parsed package version $pkg_version. Continuing..."
          else
            echo "Github ref name ${{ github.ref_name }} differs from parsed package version $pkg_version! Aborting..."
            exit 1
          fi
      - name: Publish package
        uses: gradle/gradle-build-action@v2
        with:
          build-root-directory: android
          arguments: publish
        env:
          GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
