name: Publish Website
on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  publish-website:
    name: Build Docusaurus üê≤
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
          cache-dependency-path: www/yarn.lock
      # XXX: Add API docs generation here
      - run: |
          cd www/
          yarn install --frozen-lockfile
          yarn build
      - name: Publish Latest Website
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: gh-pages
          folder: www/build
          target-folder: .
          clean: true
          clean-exclude: |
            *.*.*/
