name: Publish Docs
on:
  release:
    types: [published]

jobs:
  publish-docs:
    name: Build Docusaurus ğŸ²
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        run: |
          cd docs/
          yarn install --forzen-lockfile
          yarn build
      - name: Publish Latest Docs âœ¨
        uses: JamesIves/github-pages-deploy-action@v4.2.2
        with:
          branch: gh-pages
          folder: docs/build
          target-folder: .
          clean: true
          clean-exclude: |
            *.*.*/
