name: Publish Docs
on:
  release:
    types: [published]

jobs:
  publish-docs:
    name: Build Docusaurus ğŸ²
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - run: |
          cd docs/
          npm ci
          npm build
      - name: Publish Latest Docs âœ¨
        uses: JamesIves/github-pages-deploy-action@v4.2.2
        with:
          branch: gh-pages
          folder: docs/build
          target-folder: .
          clean: false
          clean-exclude: |
            *.*.*/
