# Workaround for the problem described here:
# https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/troubleshooting-required-status-checks
name: Swift
on:
  pull_request:
    paths-ignore:
      - "swift/**"
      - "rust/connlib/**"
      - ".github/workflows/swift.yml"
  merge_group:
    types: [checks_requested]
  workflow_call:
  workflow_dispatch:

jobs:
  swift_build:
    strategy:
      matrix:
        target:
          - sdk: macosx
            platform: macOS
            destination: platform=macOS
          - sdk: iphoneos
            platform: iOS
            destination: generic/platform=iOS
    runs-on:
      - macos-11
      - macos-12
      - macos-13
    steps:
      - run: 'echo "No build required"'
